import '@/styles/globals.css';
import type { AppProps } from 'next/app';
import React, { useReducer } from 'react';
import Head from 'next/head';
import { DefaultState, ShopContext, ShopReducer } from 'store/store-context';

function MyApp({ Component, pageProps }: AppProps) {
  const [state, dispatch] = useReducer(ShopReducer, DefaultState);
  return (
    <ShopContext.Provider value={{ state, dispatch }}>
      <Head>
        <title>Idontdrinkcoffee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </ShopContext.Provider>
  );
}

export default MyApp;
